create table tb_aluguel (id bigint generated by default as identity, data_inicio timestamp, data_termino timestamp, valor_do_contrato DOUBLE PRECISION, cliente_id bigint not null, endereco_id bigint, equipamento_id bigint not null, primary key (id));
create table tb_cliente (id bigint generated by default as identity, cpf_cnpj varchar(255), nome varchar(255), telefone1 varchar(255), telefone2 varchar(255), endereco_id bigint, primary key (id));
create table tb_endereco (id bigint generated by default as identity, bairro varchar(255), cep varchar(255), localidade varchar(255), logradouro varchar(255), numero varchar(255), uf varchar(255), primary key (id));
create table tb_equipamento (id bigint generated by default as identity, nome varchar(255), valor_aluguel_dia DOUBLE PRECISION, valor_aluguel_mes DOUBLE PRECISION, valor_aluguel_quinzena DOUBLE PRECISION, valor_da_compra DOUBLE PRECISION, primary key (id));
create table tb_role (id bigint generated by default as identity, authority varchar(255), primary key (id));
create table tb_user (id bigint generated by default as identity, email varchar(255), first_name varchar(255), last_name varchar(255), password varchar(255), primary key (id));
create table tb_user_role (user_id bigint not null, role_id bigint not null, primary key (user_id, role_id));
alter table tb_user add constraint UK_4vih17mube9j7cqyjlfbcrk4m unique (email);
alter table tb_aluguel add constraint FKbif7f2phi5iec7n7qi1msyq40 foreign key (cliente_id) references tb_cliente;
alter table tb_aluguel add constraint FK99tn89xplmpcx29s8rq6lpjm foreign key (endereco_id) references tb_endereco;
alter table tb_aluguel add constraint FKq9waeg5ur5npdi4o6gdulfr8 foreign key (equipamento_id) references tb_equipamento;
alter table tb_cliente add constraint FK69e5s70uca4u6fhiatenwcyk1 foreign key (endereco_id) references tb_endereco;
alter table tb_user_role add constraint FKea2ootw6b6bb0xt3ptl28bymv foreign key (role_id) references tb_role;
alter table tb_user_role add constraint FK7vn3h53d0tqdimm8cp45gc0kl foreign key (user_id) references tb_user;

INSERT INTO tb_user (first_name, last_name, email, password) VALUES ('Alex', 'Brown', 'alex@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG');
INSERT INTO tb_user (first_name, last_name, email, password) VALUES ('Danilo', 'silva', 'danilo_silva@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG');

INSERT INTO tb_role (authority) VALUES ('ROLE_OPERATOR');
INSERT INTO tb_role (authority) VALUES ('ROLE_ADMIN');

INSERT INTO tb_user_role (user_id, role_id) VALUES (1, 1);
INSERT INTO tb_user_role (user_id, role_id) VALUES (2, 1);
INSERT INTO tb_user_role (user_id, role_id) VALUES (2, 2);


INSERT INTO tb_endereco(cep,bairro,localidade,logradouro,numero,uf)VALUES('13481444','Santina1','Rua Delmiro Jesus Barreto','Limeira','66','SP');
INSERT INTO tb_endereco(cep,bairro,localidade,logradouro,numero,uf)VALUES('13453512','Bairro dos trabalhadores','RUa Antonio de Toledo Melo','Santa Barbara Doeste','134','SP');

INSERT INTO tb_cliente(nome,cpf_cnpj,telefone1,telefone2,endereco_id) VALUES ('Aguinaldo Ronaldo', '39119955841', '19 34455669', '19 34574589',1);
INSERT INTO tb_cliente(nome,cpf_cnpj,telefone1,telefone2,endereco_id) VALUES ('Clodoaldo Roberval', '39119955841', '19 34455669', '19 34574589',1);
INSERT INTO tb_cliente(nome,cpf_cnpj,telefone1,telefone2,endereco_id) VALUES ('Anastacio euclides', '39119955841', '19 34455669', '19 34574589',2);
INSERT INTO tb_cliente(nome,cpf_cnpj,telefone1,telefone2,endereco_id) VALUES ('Romulo afranio', '39119955841', '19 34455669', '19 34574589',2);

INSERT INTO tb_equipamento(nome,valor_da_compra,valor_aluguel_dia,valor_aluguel_quinzena,valor_aluguel_mes) VALUES ('Betoneira 01',8000.00,150.0,500.00,800.00);
INSERT INTO tb_equipamento(nome,valor_da_compra,valor_aluguel_dia,valor_aluguel_quinzena,valor_aluguel_mes) VALUES ('Betoneira 02',8000.00,150.0,500.00,800.00);
INSERT INTO tb_equipamento(nome,valor_da_compra,valor_aluguel_dia,valor_aluguel_quinzena,valor_aluguel_mes) VALUES ('Betoneira 03',8000.00,150.0,500.00,800.00);

INSERT INTO tb_aluguel(data_inicio,data_termino,valor_do_contrato,cliente_id,equipamento_id,endereco_id) VALUES ('2021-08-09','2021-08-09',800.0,1,1,1);
INSERT INTO tb_aluguel(data_inicio,data_termino,valor_do_contrato,cliente_id,equipamento_id,endereco_id) VALUES ('2022-08-09','2022-08-09',800.0,2,2,1);
INSERT INTO tb_aluguel(data_inicio,data_termino,valor_do_contrato,cliente_id,equipamento_id,endereco_id) VALUES ('2023-08-09','2023-08-09',800.0,3,3,2);